---
host2intf:
  R1:
  - {INTF: Ethernet0/0, IPADDR: 192.168.100.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/1, IPADDR: 192.168.255.1, PROTO: up, STATUS: up}
  - {INTF: Loopback100, IPADDR: 10.0.0.1, PROTO: up, STATUS: up}
  R2:
  - {INTF: Ethernet0/0.10, IPADDR: 10.2.10.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.20, IPADDR: 10.2.20.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.30, IPADDR: 10.2.30.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.40, IPADDR: 10.2.40.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.50, IPADDR: 10.2.50.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.60, IPADDR: 10.2.60.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.70, IPADDR: 10.2.70.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/2, IPADDR: 192.168.255.2, PROTO: up, STATUS: up}
  - {INTF: Loopback100, IPADDR: 10.0.0.2, PROTO: up, STATUS: up}
  R3:
  - {INTF: Ethernet0/0.10, IPADDR: 10.3.10.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.20, IPADDR: 10.3.20.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.30, IPADDR: 10.3.30.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.40, IPADDR: 10.3.40.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.50, IPADDR: 10.3.50.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.60, IPADDR: 10.3.60.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.70, IPADDR: 10.3.70.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/3, IPADDR: 192.168.255.3, PROTO: up, STATUS: up}
  - {INTF: Loopback100, IPADDR: 10.0.0.3, PROTO: up, STATUS: up}
  R4:
  - {INTF: Ethernet0/0.10, IPADDR: 10.4.10.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.20, IPADDR: 10.4.20.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.30, IPADDR: 10.4.30.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.40, IPADDR: 10.4.40.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.50, IPADDR: 10.4.50.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.60, IPADDR: 10.4.60.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/0.70, IPADDR: 10.4.70.1, PROTO: up, STATUS: up}
  - {INTF: Ethernet0/1, IPADDR: 192.168.255.4, PROTO: up, STATUS: up}
  - {INTF: Loopback100, IPADDR: 10.0.0.4, PROTO: up, STATUS: up}
