---

# Эта playbook работает с группой устройств cisco-routers.
# Строка "serial: 1" означается, что playbook будет подключаться к устройствам поочередно.
# По умолчанию подключение выполняется параллельно.

- name: Parse sh ip int br data with TextFSM
  hosts: cisco-routers
  serial: 1
  gather_facts: false
  remote_user: python

  tasks:

# Task1
#  - выполняет команду sh ip int br
#  - запоминает вывод в переменную siib_text

    - name: capture show ip interface brief
      raw: show ip interface brief | exclude unassigned
      register: siib_text

#    - name: Debug registered variables
#      debug: var=siib_text

# Task2
#  - передает переменную самописному модулю cisco_ip_intf_parse
#  - модуль cisco_ip_intf_parse парсит вывод команды с помощью TextFSM
#  - выдает результат в переменную IPs

    - name: parse the output of "show ip interface brief"
      cisco_ip_intf_parse: output_text="{{ siib_text.stdout }}"
      delegate_to: 127.0.0.1

#    - name: Debug registered variables
#      debug: var=siib_text.stdout

# Task3
#  - вызывает скрипт cisco_ip_intf_parse_write с аргументами:
#      - ipTable в который передается переменная IPs
#      - hostname имя хоста из файла inventory
#  - записывает результат в файл (указано в скрипте)

    - name: combine ip address facts and save as a global variable
      cisco_ip_intf_parse_write:
        ipTable="{{ IPs }}"
        hostname="{{ inventory_hostname }}"
      delegate_to: 127.0.0.1
