---
- name: Test new Ansible module
  hosts: ios
  gather_facts: false
  connection: local

  tasks:

    - name: Define provider variable
      set_fact:
        provider:
          host: "{{ inventory_hostname }}"
          username: "python"
          password: "python"
          auth_pass: "cisco"

 
    - name: Execute 'show version' command
      ios_command:
        provider: "{{ provider }}"
        commands:
          - show version
      register: version

    - debug: var=version.stdout_lines
