---
# В этом playbook 3 play
# Тут демонстрируется как выполнять разные задачи для разных групп устройств

# Play 1 выполняется для группы cisco-devices
- name: Run general commands
  hosts: cisco-devices
  gather_facts: false
  remote_user: python

# На всех устройствах из группы cisco-devices выполнится команда sh ip int br | ex unass

  tasks:

    - name: Run sh ip int br command
      raw: sh ip int br | ex unass
      register: sh_ip_int_br_result

# Play 2 выполняется для группы cisco-routers
- name: Run routers specific commands
  hosts: cisco-routers
  gather_facts: false
  remote_user: python

# На всех устройствах из группы cisco-routers выполнится команда sh ip route | ex -

  tasks:

    - name: Run sh ip route command
      raw: sh ip route | ex -
      register: sh_ip_route_result

# Play 3 выполняется для группы cisco-switches
- name: Run switches specific commands
  hosts: cisco-switches
  gather_facts: false
  remote_user: python

# На всех устройствах из группы cisco-switches выполнится команда sh int status | ex down

  tasks:

    - name: Run sh int status command
      raw: sh int status | ex down
      register: sh_int_status_result
