---
# Эта playbook работает с группой устройств cisco-routers.

- name: Generate and copy configuration commands to cisco
  hosts: cisco-routers
  connection: local
  gather_facts: false
  remote_user: python
  
  tasks:
  
# Task1
# Генерирует конфигурацию на основании шаблона Jinja.
# delegate_to: 127.0.0.1 означает, что шаблон генерируется локально

    - name: Create Configuration
      template: src=templates/router.j2 dest=configs/{{ hostname }}.conf
      delegate_to: 127.0.0.1

# Task2
# Вызывает скрипт generate_config.py с помощью модуля command
# Этот скрипт ожидает два аргумента: адрес устройства и конфигурационный файл
# Внутри скрипта модуль netmiko подключается к устройству и выполняет на нем команды из файла шаблона
 
    - name: Send configuration to device
      command: library/generate_config.py {{ ansible_ssh_host }} configs/{{ hostname }}.conf 
      delegate_to: 127.0.0.1
