---

- ios_facts:
    gather_subset:
      - "!hardware"
    provider: "{{ cli }}"

- name: Set fact ospf_networks
  set_fact:
    current_ospf_networks: "{{ ansible_net_config | regex_findall('network (.*) area 0') }}"

#- debug: var=current_ospf_networks

- name: Config OSPF
  ios_config:
    src: ospf.j2
    provider: "{{ cli }}"

#- name: OSPF cfg
#  ios_command:
#    commands:
#      - sh run | s ^router ospf
#    provider: "{{ cli }}"
#  register: ospf_cfg
#
#- debug: var=ospf_cfg.stdout_lines
