---
- name: example play
  hosts: all

  vars:
    http_port: 80
    max_clients: 200

  tasks:

  - name: longrunner
    command: /bin/sleep 5

  - name: write some_random_foo configuration
    template: src=templates/foo.j2 dest=/tmp/some_random_foo.conf
